version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ../databases/postgres_data:/var/lib/postgresql/data
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5000:5000"
    depends_on:
      - db
